[project]
name = "pixiv2epub"
version = "0.1.0"
description = "A tool to download novels from Pixiv and convert them into EPUB format."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "jinja2>=3.1.6",
    "pixivpy3>=3.7.5",
    "rich>=14.1.0",
]

[project.scripts]
pixiv2epub = "pixiv2epub.cli:main"

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
